#!/usr/bin/env bash

# Instala lm-sensors si no está instalado
if ! command -v sensors &> /dev/null
then
    echo "lm-sensors no está instalado. Instalándolo..."
    sudo apt-get install lm-sensors
fi

# Detecta los sensores de hardware
sudo sensors-detect --auto

# Obtiene y muestra la temperatura de la CPU
TEMP=$(sensors | awk '/^temp1/ {print $2}')
echo "${TEMP:-null}"
