#!/usr/bin/env bash

launch_bars() {
    eww -c ~/.config/bspwm/bar open --toggle bar
#    eww -c ~/.config/bspwm/bar open --toggle bar2
}

### ---------- Apply Configurations ---------- ###

launch_bars
