#!/bin/bash

# A script to toggle between various desktop layouts for bspwm, intended to be used for my polybar module.

# Get the current layout
CURRENT=$(bsp-layout get)

# Switch layouts

# Tiled
if [[ $CURRENT == "tiled" ]]; then
        bsp-layout set monocle
        echo "󰨤"
        exit
fi

# Monocle
if [[ $CURRENT == "monocle" ]]; then
        bsp-layout set tall
        echo "󰕮"
        exit
fi

# Grid
if [[ $CURRENT == "tall" ]]; then
        bsp-layout set wide
        echo "󰕪"
        exit
fi

# Wide
if [[ $CURRENT == "wide" ]]; then
        bsp-layout set even
        echo "󰍲"
        exit
fi

# Even
if [[ $CURRENT == "even" ]]; then
        bsp-layout set tiled
        echo "󰙀"
        exit
fi
