#!/bin/bash

active_window_id=$(xdotool getactivewindow 2>/dev/null)
if [ "$active_window_id" != "0" ] && [ -n "$active_window_id" ]; then
    window_class=$(xprop -id $active_window_id | awk -F '=' '/WM_CLASS/ {print $2}' | tr -d ' "')
else
    window_class=""
fi

case $window_class in
    *firefox*)
        echo " "  
        ;;
    *org.wezfurlong.wezterm*)
        echo " "  
        ;;
    *Thunar*)
        echo " "  
        ;;
    *copyq*)
        echo "󱓥 "  
        ;;
    *stalonetray*)
        echo "󱊖 "  
        ;;
    *blueberry.py*)
        echo " "  
        ;;
    *pavucontrol*)
        echo "󱡫 "  
        ;;
    *YouTube*)
        echo "󰗃 "  
        ;;
    *code-oss*)
        echo "󰨞 "  
        ;;
    *Wezterm*)
        echo " "  
        ;;
    *alacritty*)
        echo " "  
        ;;
    *Alacritty*)
        echo " "  
        ;;
    *gimp-2.10*)
        echo "󱋆 "  
        ;;
    *Mugshot*)
        echo "󰚼 "  
        ;;
    *xfce4-about*)
        echo "󱋅 "  
        ;;
    *audacity*)
        echo " "  
        ;;
    *qt5ct*)
        echo " "  
        ;;
    *cmake-gui*)
        echo " "  
        ;;
    *amberol*)
        echo "󱍙 "  
        ;;
    *ark*)
        echo " "  
        ;;
    *BleachBit*)
        echo " "  
        ;;
    *clamtk*)
        echo " "  
        ;;
    *nm-connection-editor*)
        echo "󰤤 "  
        ;;
    *avahi-discover*)
        echo "󰤤 "  
        ;;
    *corectrl*)
        echo " "  
        ;;
    *soffice*)
        echo "󰏆 "  
        ;;
    *libreoffice*)
        echo " "  
        ;;
    *atril*)
        echo "󱔘 "  
        ;;
    *lxappearance*)
        echo "󱕷 "  
        ;;
    *kvantummanager*)
        echo "󱕷 "  
        ;;
    *steam*)
        echo "󰓓 "  
        ;;
    *zenity*)
        echo "󰓓 "  
        ;;
    *retroarch*)
        echo "󰺵 "  
        ;;
    *heroic*)
        echo "󰡶 "  
        ;;
    *geany*)
        echo " "  
        ;;
     *Godot*)
        echo " "  
        ;;
     *gpartedbin*)
        echo "󱊞 "  
        ;;
     *electron*)
        echo "󱀤 "  
        ;;
      *)
        echo "󰋜 "  
        ;;
     esac
