#!/bin/bash

# -----------------------------------------------------------------------------------
#
# ██╗   ██╗████████╗███╗   ███╗██████╗ ██████╗ 
# ╚██╗ ██╔╝╚══██╔══╝████╗ ████║██╔══██╗╚════██╗
#  ╚████╔╝    ██║   ██╔████╔██║██████╔╝ █████╔╝
#   ╚██╔╝     ██║   ██║╚██╔╝██║██╔═══╝  ╚═══██╗
#    ██║      ██║   ██║ ╚═╝ ██║██║     ██████╔╝
#    ╚═╝      ╚═╝   ╚═╝     ╚═╝╚═╝     ╚═════╝ 
#
# ----- Author: Shen - url: https://github.com/Shentxt -----

# music folder
if [[ -d "${XDG_MUSIC_DIR:-$HOME/Music}" ]]; then
    MUSIC_DIR="${XDG_MUSIC_DIR:-$HOME/Music}"
elif [[ -d "$HOME/Música" ]]; then
    MUSIC_DIR="$HOME/Música"
else
    echo "folder not found"
    exit 1
fi

# Menu
function mostrar_menu {
    echo "1) Download Music"
    echo "2) Exit"
}

# while
while true; do
    mostrar_menu
    read -p "Choose an option: " opcion
    case $opcion in
        1)
            read -p "Enter the url of YT: " url
            if yt-dlp -x --audio-format mp3 --audio-quality 0 -P "$MUSIC_DIR" -o "%(title)s.%(ext)s" "$url"; then
                notify-send "Ren" "new soundtrack? amazing it's time to try it." -i ~/.config/bspwm/assets/icons/persona/ren.png
            else
                notify-send "Futaba" "Oops! It seems there was a problem with the URL you entered. Please try again." -i ~/.config/bspwm/assets/icons/persona/futaba.png
            fi
            ;;
        2)
            break
            ;;
        *)
            echo "invalid option"
            ;;
    esac
done
