#!/usr/bin/env bash

# -------------------------------------------
#
#  ╔═╗═╗ ╦╔╦╗╔═╗╦═╗╔╗╔╔═╗╦    ╦═╗╦ ╦╦  ╔═╗╔═╗
#  ║╣ ╔╩╦╝ ║ ║╣ ╠╦╝║║║╠═╣║    ╠╦╝║ ║║  ║╣ ╚═╗
#  ╚═╝╩ ╚═ ╩ ╚═╝╩╚═╝╚╝╩ ╩╩═╝  ╩╚═╚═╝╩═╝╚═╝╚═╝
#
# ----- Author: Shen - url: https://github.com/Shentxt -----

#|||----- Info -----|||#

wid=$1
class=$2
instance=$3
consequences=$4

# ------------------------------------------------------------

#|||----- Rules -----|||#

case "$class" in
FloaTerm)
	eval "$consequences"
	[ "$state" ] || echo "state=floating  rectangle=849x477+0+0 center=on"
	;;
Alacritty)
	eval "$consequences"
	[ "$state" ] || echo "state=floating  rectangle=849x477+0+0 center=on"
	;;
Updating)
	eval "$consequences"
	[ "$state" ] || echo "state=floating sticky=on  rectangle=849x477+0+0 center=on"
	;;
mpv)
	eval "$consequences"
	[ "$state" ] || echo "state=floating focus=on rectangle=849x477+0+0 center=on"
	;;
Viewnior)
	eval "$consequences"
	[ "$state" ] || echo "state=floating focus=on center=on"
	;;
whatsapp-nativefier-d40211 | TelegramDesktop)
	eval "$consequences"
	[ "$state" ] || echo "state=pseudo_tiled folow=on"
	;;
Pavucontrol)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
Virt-manager)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on center=on"
	;;
Thunar)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
Transmission-gtk)
	eval "$consequences"
	[ "$state" ] || echo "follow=on"
	;;
Spotify)
	eval "$consequences"
	[ "$state" ] || echo "state=pseudo_tiled follow=on"
	;;
esac

# ------------------------------------------------------------------

#|||----- Extra -----|||#

case "$instance" in
kvantummanager)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
qt5ct)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
ark)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
blueman-manager)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0  center=on"
	;;
blueberry.py)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
lxappearance)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
feh)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=849x477+0+0 center=on"
	;;
copyq)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=450x400+890+75" 
	;;
Youtube_Music)
  eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on rectangle=450x400+890+75" 
	;;
zenity)
	eval "$consequences"
	[ "$state" ] || echo "state=floating follow=on center=on"
	;;
Toolkit)
	eval "$consequences"
	[ "$state" ] || echo "state=floating rectangle=450x400+890+75 sticky=on"
	;;
esac
