#!/usr/bin/env bash

# ------------------------------------------------------------------------
# ██╗  ██╗██╗██████╗ ███████╗██████╗  █████╗ ██████╗ 
# ██║  ██║██║██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗
# ███████║██║██║  ██║█████╗  ██████╔╝███████║██████╔╝
# ██╔══██║██║██║  ██║██╔══╝  ██╔══██╗██╔══██║██╔══██╗
# ██║  ██║██║██████╔╝███████╗██████╔╝██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝╚═════╝ ╚══════╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
# ----- Author: Shen - url: https://github.com/Shentxt -----

conf_file="$HOME/.config/bspwm/Theme.sh"
T_Padding=$(grep "bspc config top_padding" "$conf_file" | awk '{print $NF}')
B_Padding=$(grep "bspc config bottom_padding" "$conf_file" | awk '{print $NF}')
L_Padding=$(grep "bspc config left_padding" "$conf_file" | awk '{print $NF}')
R_Padding=$(grep "bspc config right_padding" "$conf_file" | awk '{print $NF}')

hide() {
	(polybar-msg cmd hide)
	(bspc config top_padding 2)
	(bspc config bottom_padding 2)

	if pgrep -f 'eww.*bar'; then
			(eww -c "$HOME"/.config/bspwm/bar open --toggle bar)
      (eww -c "$HOME"/.config/bspwm/bar open --toggle bar2)
			(bspc config left_padding 2)
			(bspc config right_padding 2)
		fi
}

unhide() {
	(polybar-msg cmd show)
	(bspc config top_padding "$T_Padding")
	(bspc config bottom_padding "$B_Padding")

	if pgrep -f 'eww.*bar'; then
    (eww -c "$HOME"/.config/bspwm/bar open --toggle bar)
    (eww -c "$HOME"/.config/bspwm/bar open --toggle bar2)
			(bspc config left_padding "$L_Padding")
			(bspc config right_padding "$R_Padding")
		fi
}

case $1 in
  -h)
	  hide;;
  -u)
	  unhide;;
esac
