#!/usr/bin/env bash

# -------------------------------------------------------------------------------------------------------
#
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#
# ----- Author: Shen - url: https://github.com/Shentxt -----

#|||----- Info -----|||#

WIDGET_DIR="$HOME/.config/bspwm/eww"

# -----------------------------------------------------------

#|||----- Launch -----|||#

case "$1" in
--menu)
	rofi -show drun -theme $HOME/.config/rofi/themes/default.rasi
	;;
--power)
  ~/.config/bspwm/bar/scripts/powermenu
  ;;
--root)
	~/.config/bspwm/scripts/bsproot
	;;
--record)
  ~/.config/bspwm/scripts/Recording
  ;;
--shot)
	~/.config/bspwm/scripts/Screenshot
	;;
--note)
	~/.config/bspwm/scripts/notes
	;;
--color)
	~/.config/bspwm/scripts/colorpicker
	;;
--user)
	mugshot
	;;
--wine)
	winetricks
	;;
--lock)
	betterlockscreen -l
	;;
--terminal)
	wezterm
	;;
# Float Launch
--floating)
	alacritty --class FloaTerm,alacritty -o window.dimensions.lines=22 window.dimensions.columns=90
  ;;
--update)
	alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
	;;
--checkupdates)
	alacritty --hold --class Updating,Updating -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
	;;
--ranger)
	alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
	;;
--nvim)
	alacritty -e nvim
	;;
--music)
  alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90 -e ytmp3	
	;;
--send)
  alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90 -e send	
  ;;
--show)
  python3 ~/.config/bspwm/bar/scripts/show.py  
  ;;
--fetch)
	alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
	;;
# Apps
--filemanager)
	thunar
	;;
--browser)
	firefox
	;;
--editor)
	geany
	;;
--telegram)
	telegram-desktop
	;;
--whats)
	whatsapp-nativefier --disable-gpu
	;;
--soundcontrol)
	pavucontrol
	;;
*)
	echo "invalid option"
	;;
esac
