#!/usr/bin/env bash

# -------------------------------------------------------------------------------------------------------
#
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#
# ----- Author: Shen - url: https://github.com/Shentxt -----

#|||----- Info -----|||#

WIDGET_DIR="$HOME/.config/bspwm/bar/eww"

# -----------------------------------------------------------

#|||----- Launch -----|||#

case "$1" in
--menu)
	rofi -show drun -theme $HOME/.config/rofi/themes/default.rasi
	;;
--jgmenu)
  xqp 0 $(xdo id -N Bspwm -n root) && jgmenu --csv-file=~/.config/bspwm/jgmenu/menu.txt --config-file=~/.config/bspwm/jgmenu/jgmenurc
  ;;
--game)
  ~/.config/bspwm/bar/scripts/gamemode
  ;;
--power)
  ~/.config/bspwm/bar/scripts/powermenu
  ;;
--high)
  ~/.config/bspwm/bar/scripts/noti-volum --inc
  ;;
--low)
  ~/.config/bspwm/bar/scripts/noti-volum --dec
  ;;
--root)
	~/.config/bspwm/scripts/bsproot
	;;
--record)
  ~/.config/bspwm/scripts/Recording
  ;;
--shot)
	~/.config/bspwm/scripts/Screenshot
	;;
--note)
	~/.config/bspwm/scripts/notes
	;;
--color)
	~/.config/bspwm/scripts/colorpicker
	;;
--cli)
  ~/.config/bspwm/bar/scripts/clip
  ;;
--windows)
  ~/.config/bspwm/scripts/windoview
  ;;
--wine)
	winetricks
	;;
--lock)
	betterlockscreen -l
	;;
--terminal)
	wezterm
	;;
--user)
	mugshot
	;;
# Float Launch
--floating)
	kitty --class FloaTerm
  ;;
--update)
  kitty --hold --class FloaTerm -e Updates --update-system
	;;
--checkupdates)
	kitty --hold --class Updating -e Updates --print-updates
	;;
--editor)
	kitty -e nvim
	;;
--wifi)
  kitty -e nmtui 
  ;;
--wi)
  kitty -e sudo iptraf-ng 
  ;;
--music)
  kitty --hold --class FloaTerm -e ytmp3	
	;;
--send)
  kitty --hold --class FloaTerm -e send	
  ;;
# Apps
--filemanager)
	thunar
	;;
--browser)
	firefox
	;;
--editor)
	geany
	;;
--telegram)
	telegram-desktop
	;;
--whats)
	whatsapp-nativefier --disable-gpu
	;;
--soundcontrol)
	pavucontrol
	;;
--usercard)
  eww -c "$WIDGET_DIR" open --toggle launchermenu
  ;;
--player)
  eww -c "$WIDGET_DIR" open --toggle  musiccenter
  ;;
--calendar)
  eww -c "$WIDGET_DIR" open --toggle date
  ;;
*)
	echo "invalid option"
	;;
esac
