#!/bin/sh

calendar(){
LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="$HOME/.local/bin/eww"

run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
}

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    ${EWW_BIN} -c $HOME/.config/bspwm/bar/eww/bar close calendar
    rm "$LOCK_FILE"
fi
}

if [ "$1" = "wifi" ]; then
alacritty -e nmtui
elif [ "$1" = "audio" ]; then
pavucontrol
elif [ "$1" = "calendar" ]; then
calendar
fi
